"""ig_messages inbox

Revision ID: cd0f8adef9ce
Revises: 72dd18b7ed47
Create Date: 2026-06-20 15:37:41.748116
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# идентификаторы ревизии для Alembic
revision: str = 'cd0f8adef9ce'
down_revision: Union[str, None] = '72dd18b7ed47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ig_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('igsid', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('out', sa.Boolean(), nullable=False),
    sa.Column('mid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['social_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ig_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ig_messages_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ig_messages_igsid'), ['igsid'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ig_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ig_messages_igsid'))
        batch_op.drop_index(batch_op.f('ix_ig_messages_account_id'))

    op.drop_table('ig_messages')
    # ### end Alembic commands ###
