"""kanban boards

Revision ID: 72dd18b7ed47
Revises: 4d94f4cdeba7
Create Date: 2026-06-17 16:55:34.699993
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# идентификаторы ревизии для Alembic
revision: str = '72dd18b7ed47'
down_revision: Union[str, None] = '4d94f4cdeba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kanban_boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=False),
    sa.Column('placements', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['social_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'account_id', name='uq_kanban_user_account')
    )
    with op.batch_alter_table('kanban_boards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kanban_boards_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kanban_boards_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kanban_boards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kanban_boards_user_id'))
        batch_op.drop_index(batch_op.f('ix_kanban_boards_account_id'))

    op.drop_table('kanban_boards')
    # ### end Alembic commands ###
